public class jsonExample1 {
    
/*    public String str {set;get;}
    public List<Account> acc {set;get;}
    public String jsonstr {set;get;}
    public String student {set;get;}
    public jsonExample1(){
        student s=new student('vineet');
        str='vineet';
        acc=[select id,name,industry from account limit 1];
        
        
        str=JSON.serialize(str);
        jsonstr=JSON.serializePretty(acc);
        
        student=JSON.serialize(s);
    }
    
*/
}