public class MapClass {
    public string BillingStreet {set;get;}
        public string Name {set;get;}
    public string BillingPostalCode {set;get;}
    public string BillingCity {set;get;}
   
        public string BillingState {set;get;}
    public string BillingCountry {set;get;}
    
    public MapClass()
    {
        BillingStreet='Rajat path,Mansarovar';
        BillingPostalCode='302020';
        BillingCity='jaipur';
        BillingState='rajasthan';
        BillingCountry='india';
        name='vineet';
        
        
    }

}