public class WrapperController {
/*   public  WrapperController(ApexPages.StandardSetController controller)
   {}
    public List<Wrapper> wrapAccounts {set;get;}
    public list<account> selectedAccounts{get;set;}
    public WrapperController()
    {
       
        if(wrapAccounts==null)
        {
             wrapAccounts=new List<Wrapper>();
        for(Account a:[select name,phone from account limit 10])
        {
            wrapAccounts.add(new Wrapper(a)); 
        }
        
        }
    }
    
    public void showselected()
    {
         selectedAccounts=new list<account>();
        for(Wrapper wrapobj:wrapAccounts){
           if(wrapobj.flag==true){
           selectedAccounts.add(wrapobj.acc);
           
         }

    }

    }  */
}